// Tests the distribution generated by Java's Math.random() function.

import javax.swing.text.AbstractDocument.LeafElement;

public  class  TestRandom {
	public static void main(String[]  args) {
	    // I need to get from the user how many time we want to run num between 0-1
		// I need to count each one above and under or equal 0.5
		// and after I need the ratio 
		int GreaterThan = 0;
		int LessThan = 0 ;
		int N = Integer.parseInt(args[0]);
		for (int i=0;  i <= N ; i++) {
			double Test = Math.random();
			if (Test > 0.5){
				GreaterThan++;
			}else{
				LessThan++;
			}
		}
		System.out.println("> 0.5: " + GreaterThan + " times");
		System.out.println("<= 0.5: " + LessThan + " times");
		if (LessThan > 0){
		double Ratio = (double) GreaterThan / LessThan;
		System.out.println("Ratio: " + Ratio); 	
		}
	}
}
